Vítejte v TeX Live

   Softwarová distribuce TeX Live nabízí kompletní TeXový systém pro řadu
   platforem - GNU a UNIX, Macintosh, Windows a další. Zahrnuje programy
   pro editování, sazbu, zobrazení a tisk TeXových dokumentů v mnoha
   různých jazycích a rozsáhlou kolekci TeXových maker a fontů.

   Distribuce zahrnuje obsáhlou dokumentaci o TeXu obecně, stejně jako
   dokumentaci k zahrnutým softwarovým balíkům.

   Informaci o licencích najdete v kořenovém adresáři v textových
   souborech [1]LICENSE.TL a [2]LICENSE.CTAN.
  
  Kde začít

   Důrazně doporučujeme, abyste si ještě před instalací přečetli průvodce
   TeX Live. Průvodce obsahuje instrukce "krok za krokem", popis hlavních
   adresářů a další informace.

   Pokud instalujete z DVD, anglické i další jazykové verze instalačních
   průvodců jsou umístěny v podadresáři [3]texlive-doc.
 
   Po instalaci, anglické verze Průvodce instalací najdete v adresářové 
   struktuře [4]texmf-dist/doc/texlive ve formátech [5]html i [6]pdf. 
   Překlady do dalších jazyků jsou také dostupné v podstromu 
   [7]texmf-dist/doc/texlive.

   Nabízíme také [8]seznam odkazů na dostupnou dokumentaci k zahrnutým
   balíkům a programům, opět ve formátech HTML a PDF.

   Pokud instalujete z internetu, výše zmíněné odkazy vám nebudou fungovat.
   V tom případě si ale můžete [9]dokumentaci TeX Live prohlížet
   na internetu.

   Seznam nejdůležitějších změn v letošním vydání najdete v oddílu
   Historie verzí na konci dokumentace.

  Instalace

   Instalační skript se jmenuje install-tl (install-tl.bat pod Windows)
   a můžete jej spustit ve třech režimech:

   průvodce (standardní spuštění pod Windows), který se vás zeptá jen na
          nutné minimum otázek a instalaci pak provede sám. Tento režim
          vyberete spuštěním install-tl --gui=wizard.

   text (standardní spuštění pro všechny ostatní systémy), který 
          nabízí všechny možnosti přizpůsobení instalace. Tento režim
          vyberete spuštěním install-tl --gui=text.

   perltk, který je GUI v textovém režimu; je užitečný pro zkušené
          uživatele Windows, kteří nechtějí použít standardní
          nastavení. Instalaci v tomto režimu je možné zvolit buď
          spuštěním install-tl --gui=perltk, nebo spuštěním souboru
          install-tl-advanced.bat pod Windows.

   Dodatečné aktualizace balíků a další konfigurace se vykonávají
   pomocí skriptu tlmgr (TeX Live Package Manager), který má také
   režimy GUI i textový.

   Spuštěním programů [10]install-tl i [11]tlmgr s volbou --help
   získáte podrobnou informaci o obou programech. (Mnohem) více
   informací získáte pomocí odkazů na dokumentaci zmíněných výše.

  Odkazy

   Na závěr pro vaši informaci uvádíme několik relevantních webových
   stránek, které nejsou součástí TeX Live:

     * [12]http://tug.org/begin.html - pokud jste TeXový začátečník a/nebo
       máte zájem o úvodní materiály.
     * [13]http://tug.org/interest.html - všeobecný seznam TeXových zdrojů
       na webu, zahrnující dokumentaci, systémy, balíky, fonty a další.
     * [14]http://tug.org/ctan.html - jeden z přístupových bodů k archivu
       Comprehensive TeX Archive Network (CTAN). Tento archiv slouží jako
       online repozitář všech věcí souvisejících s TeXem.
     * [15]http://tug.org/usergroups.html - seznam uživatelských skupin TeXu
       z celého světa, spolu s kontaktními informacemi. Rozhodně vám
       doporučujeme abyste se stali členy jedné z těchto skupin,
       například CSTUG [16]http://www.cstug.cz. Podpoříte
       tím TeX Live a další TeXové aktivity.

    Příjemné TeXování!
     _________________________________________________________________

   [17]Domovská stránka TeX Live.

Odkazy

   1. file:../LICENSE.TL
   2. file:../LICENSE.CTAN
   3. file:../texlive-doc
   4. file:../texmf-dist/doc/texlive/texlive-en
   5. file:../texmf-dist/doc/texlive/texlive-en/texlive-en.html
   6. file:../texmf-dist/doc/texlive/texlive-en/texlive-en.pdf
   7. file:../texmf-dist/doc/texlive/
   8. file:../doc.html
   9. http://tug.org/texlive/doc.html
  10. http://tug.org/texlive/doc/install-tl.html
  11. http://tug.org/texlive/tlmgr.html
  12. http://tug.org/begin.html
  13. http://tug.org/interest.html
  14. http://tug.org/ctan.html
  15. http://tug.org/usergroups.html
  16. http://www.cstug.cz
  17. http://tug.org/texlive/
