#!/bin/sh
##
##  pdf90: A shell program to rotate pages of PDF files
##
##  Author David Firth (http://go.warwick.ac.uk/dfirth)
##
##  This is a simple wrapper for pdfjam, version 2.08
##
exec pdfjam --suffix rotated90 --angle 90 --fitpaper true --rotateoversize true "$@"


