#!/bin/sh
##
##  pdfjoin: A shell program to concatenate PDF files
##
##  Author David Firth (http://go.warwick.ac.uk/dfirth)
##
##  This is a simple wrapper for pdfjam, version 2.08
##
E_USAGE=64           ##  for a command line usage error
for arg
do
    case $arg in
	--batch)
	    printf "pdfjoin ERROR: the --batch option is not allowed\n" 1>&2; 
	    exit "$E_USAGE" ;;
	--orient)  ## this was allowed in previous versions of pdfjoin
	    printf "pdfjoin ERROR: the --orient option is not allowed,\n" 1>&2;
	    printf "  use --landscape or --no-landscape to specify\n" 1>&2;
	    printf "  the output page orientation" 1>&2;
	    exit "$E_USAGE" ;;
	*) continue ;;
    esac
done
exec pdfjam --fitpaper true --rotateoversize true --suffix joined "$@"


