#!/bin/sh
##
##  pdfjam-slides6up: A shell program to make a 6-up "handout" 
##  of presentation slides
##
##  Author David Firth (http://go.warwick.ac.uk/dfirth)
##
##  This is a simple wrapper for pdfjam, version 2.08
##
footskip=2.7cm                           ## default setting
pagecommand='{\thispagestyle{empty}}'    ## default setting
case ${1} in
    --pagenumbering)
	case ${2} in
	    false)
		continue ;;
	    true)
		pagecommand='{\thispagestyle{plain}}' ;;
	    *)       ## a footskip dimension was supplied
		pagecommand='{\thispagestyle{plain}}' ;
		footskip="$2" ;;
	esac ;
	shift; shift ;;
    *)
	continue ;;
esac
exec pdfjam --suffix 6up --nup 2x3 --frame true --noautoscale false \
  --delta "0.2cm 0.3cm" --scale 0.95 --preamble "\footskip $footskip" \
  --pagecommand "$pagecommand" "$@"


