#!/bin/sh
##
##  pdf270: A shell program to rotate pages of PDF files
##
##  Author David Firth (http://go.warwick.ac.uk/dfirth)
##
##  This is a simple wrapper for pdfjam, version 2.08
##.
exec pdfjam --suffix rotated270 --angle 270 --fitpaper true --rotateoversize true "$@"


