#!/bin/sh
##
##  pdfflip: A shell program to "flip over" the pages of PDF files
##
##  Author David Firth (http://go.warwick.ac.uk/dfirth)
##
##  This is a simple wrapper for pdfjam, version 2.08
##
exec pdfjam --suffix flipped --reflect true --fitpaper true  "$@"
