#!/bin/sh
##
##  pdfjam-slides3up: A shell program to make a 3-up "handout" 
##  of presentation slides, with space for side-notes
##
##  Author David Firth (http://go.warwick.ac.uk/dfirth)
##
##  This is a simple wrapper for pdfjam, version 2.08
##
footskip=3.1cm                           ## default setting
pagecommand='{\thispagestyle{empty}}'    ## default setting
case ${1} in
    --pagenumbering)
	case ${2} in
	    false)
		continue ;;
	    true)
		pagecommand='{\thispagestyle{plain}}' ;;
	    *)       ## a footskip dimension was supplied
		pagecommand='{\thispagestyle{plain}}' ;
		footskip="$2" ;;
	esac ;
	shift; shift ;;
    *)
	continue ;;
esac
exec pdfjam --suffix 3up --nup 1x3 --frame true --noautoscale false \
  --delta "0cm 0.2cm" --scale 0.87 --offset "-3.8cm 0cm" \
  --preamble "\footskip $footskip" --pagecommand "$pagecommand" "$@"
