#!/bin/sh
##
##  pdfnup: A shell program to n-up pages of PDF files
##
##  Author David Firth (http://go.warwick.ac.uk/dfirth)
##
##  This is a simple wrapper for pdfjam, version 2.08
##
E_USAGE=64           ##  for a command line usage error
for arg
do
    case $arg in
	--orient)  ## this was allowed in previous versions of pdfnup
	    printf "pdfnup ERROR: the --orient option is not allowed,\n" 1>&2;
	    printf "  use --landscape or --no-landscape to specify\n" 1>&2;
	    printf "  the output page orientation" 1>&2;
	    exit "$E_USAGE" ;;
	--pages)  ## this was allowed in previous versions of pdfnup
	    printf "pdfnup ERROR: the --pages option is not allowed,\n" 1>&2;
	    printf "  see 'pdfjam --help' or http://go.warwick.ac.uk/pdfjam\n" \
		1>&2;
	    printf "  for page selection examples\n" 1>&2;
	    exit "$E_USAGE" ;;
	*) continue ;;
    esac
done
exec pdfjam --suffix nup --nup 2x1 --landscape "$@"


