.TH allcm 1 "11/94" "teTeX" "teTeX"
.SH NAME
allcm \- force the most important Computer\-Modern\-fonts to be calculated
.SH SYNOPSIS
.B allcm [-r]
.SH DESCRIPTION
.I allcm
forces a large number of Computer Modern Fonts to be calculated as pixel files.
This is done through running
.IR dvips (1)
over a certain test-file. Therefore, the fonts are created in the resolution
needed by dvips.

If the \-r flag is specified, the command
.IR dvired (1)
will be used instead of dvips.

.I allcm
does not recalculate existing fonts (as long as the Metafont mode does not change).

.SH "SEE ALSO"
allec(1),
allneeded(1),
dvips(1),
dvired(1).

.SH AUTHOR
Thomas Esser <te@dbs.uni-hannover.de>
