.TH alldc 1 "11/94" "teTeX" "teTeX"
.SH NAME
allec \- force the most important ec\-fonts to be calculated
.SH SYNOPSIS
.B allec [\-r]
.SH DESCRIPTION
.I allec
forces a large number of ec-style Fonts to be calculated as pixel files.
This is done through running
.IR dvips (1)
over a certain test-file. Therefore, the fonts are created in the resolution
needed by dvips.

If the \-r flag is specified, the command
.IR dvired (1)
will be used instead of dvips.

.I alldc
does not recalculate existing fonts (as long as the Metafont mode does not change).

.SH "SEE ALSO"
allcm(1),
allneeded(1),
dvips(1),
dvired(1).

.SH AUTHOR
Thomas Esser <te@dbs.uni-hannover.de>
