.TH allneeded 1 "11/94" "teTeX" "teTeX"
.SH NAME
allneeded \- force the calculation of all fonts now needed
.SH SYNOPSIS
.B allneeded [\-r] files ...
.SH DESCRIPTION
.I allneeded
forces the calculation of all fonts that are needed to preview a set of
dvi files. Just specify where the program should search for files on the
commandline.
The fonts generation is triggered by running
.IR dvips (1)
over all accessible dvi\-files. Therefore, the fonts are created in the resolution
needed by dvips.

If the \-r flag is specified, the command
.IR dvired (1)
will be used instead of dvips.

.I allneeded
does not recalculate existing fonts (as long as the Metafont mode does not change).

.SH "SEE ALSO"
allec(1),
allcm(1),
dvips(1),
dvired(1).

.SH AUTHOR
Thomas Esser <te@dbs.uni-hannover.de>
