.TH "dvipdft" "1" "May 2004" "teTeX" "teTeX" 
.PP 
.SH "NAME" 
dvipdft \- create thumbnail images for use with dvipdfm
.PP 
.SH "SYNOPSIS" 
.PP 
.B dvipdft
.RI [ DVIPDFM-OPTIONS \&.\&.\&.]
.I filename\c
.RB [ .dvi ]
.PP 
.SH "DESCRIPTION" 
.PP 
.B dvipdft
creates thumbnail pictures of the pages in your file
and subsequently runs dvipdfm to create a PDF file with these
thumbnails. 
.PP
.SH "OPTIONS" 
.HP
All options are simply handed on to dvipdfm
.HP
.SH "SEE ALSO" 
.IP 
\fBdvipdfm\fP(1)
.PP 
.SH "BUGS" 
.PP 
None known\&.
.PP 
.SH "AUTHOR" 
.PP 
\fBdvipdft\fP was written by Mark A. Wicks and Thomas Esser.
.PP 
This manual page was written by Frank K\[:u]ster <frank@kuesterei\&.ch>,
for the Debian GNU/Linux system\&.  It may be used by others without
contacting the author\&.  Any mistakes or omissions in the manual page
are my fault; inquiries about or corrections to this manual page
should be directed to me (and not to the primary author)\&.
