.TH FMTUTIL 1 "June 2011" "TeX Live" "TeX Live"
.SH "NAME"
fmtutil \- utility for maintaining TeX format files
.PP
fmtutil-sys \- utility for maintaining TeX format files system\-wide
.SH "SYNOPSIS"
.B fmtutil\fP
.RI [ OPTION .\|.\|.]
.I COMMAND
.PP
.B fmtutil-sys
.RI [ OPTION .\|.\|.]
.I COMMAND
.SH "DESCRIPTION"
\fBfmtutil\fP is used to create or recreate format and hyphenation
files or show information about format files\&.
.PP
\fICOMMAND\fP is one of:
.PP
.TP
.B --all
recreate all format files
.TP
.BI --byengine \ enginename
(re)create formats that depend on the
engine \fIenginename\fP
.TP
.BI --byfmt \ formatname
(re)create the format for
format \fIformatname\fP
.TP
.BI --byhyphen \ hyphenfile
(re)create formats that depend on the
hyphenation file \fIhyphenfile\fP
.TP
.B --catcfg
output the content of the config file
.TP
.BI --disablefmt \ formatname
disable
.I formatname
in config file
.TP
.B --edit
no-op in TeX Live
.TP
.BI --enablefmt \ formatname
ensable
.I formatname
in config file
.TP
.B --help
print a summary of commands and options
.TP
.B --listcfg
list (enabled and disabled) configurations, filtered to available formats
.TP
.B --missing
create all missing format files
.TP
.B --refresh
recreate only existing format files
.TP
.BI --showhyphen \ formatname
print the name of the
hyphenation file for the format
\fIformatname\fP
.TP
.B --version
show version info
.SH "OPTIONS"
.TP
.BI --cnffile \ file
specify the configuration
\fIfile\fP \fBfmtutil\fP should use
.TP
.B --dolinks
(not implemented, just for compatibility)
.TP
.BI --fmtdir \ directory
set the destination
directory for format files generated by
\fBfmtutil\fP to \fIdirectory\fP
.TP
.B --force
(not implemented, just for compatibility)
.TP
.B --no-engine-subdir
don't use engine-specific subdir of the fmtdir
.TP
.B --no-error-if-no-format
exit successfully if no format is selected
.TP
.B --quiet
be silent
.TP
.B --test
(not implemented, just for compatibility)
.SH "FILES"
.TP
.I fmtutil\&.cnf
default configuration file
.SH "SEE ALSO"
.BR kpsewhich (1)
.SH "BUGS"
None known, but report any bugs found to <tex-k@tug.org> (mailing list).
.SH "AUTHOR"
\fBfmtutil\fP was written by Thomas Esser
<te@dbs\&.uni-hannover\&.de> and is in the public domain.
.PP
This manual page was written by C\&.M\&. Connelly
<c@eskimo\&.com>, for
the Debian GNU/Linux system and later slightly adapted for the teTeX 3 release\&.
