.TH KPSEREADLINK 1 "1 March 2011" "Kpathsea 6.1.1"
.\"=====================================================================
.SH NAME
kpsereadlink \- print contents of symbolic link
.SH SYNOPSIS
.B kpsereadlink
.I file
.\"=====================================================================
.SH DESCRIPTION
If
.I file
is a symbolic link, print its contents (what it links to), and exit
successfully.  Exit with a failure otherwise.
.PP
On systems that do not support symbolic links,
.B kpsereadlink
will always fail.
.\"=====================================================================
.SH OPTIONS
.B kpsereadlink
accepts the following options:
.TP
.B --help
Print help message and exit.
.TP
.B --version
Print version information and exit.
.\"=====================================================================
.SH "SEE ALSO"
.BR readlink (2)
