.TH "mkocp" "1" "September 2000" "Omega" "Omega" 
.PP 
.SH "NAME" 
mkocp \- frontend to \fBotp2ocp\fP(1)
.SH "SYNOPSIS" 
.B mkocp
.I OTPFILE
.SH "DESCRIPTION" 
.PP 
\fBmkocp\fP is used to create or recreate Omega Compiled Process files
(binary) from Omega Translation Process (text) files\&.
.PP 
Omega Translation Processes are used to translate one character set to
another and to choose between characters with one or more
context-sensitive variants\&.  OTPs could also be used to change the
case or hyphenation of text\&.
.PP 
OTPs are defined in text files, and compiled into binary code (OCPs)
using \fBmkocp\fP (this script) or directly with \fBotp2ocp\fP(1)\&.
.PP 
.SH "FILES" 
.IP "\fIOTPFILE\fP" 
An Omega Typesetting Process filter file\&.
.PP 
.SH "SEE ALSO" 
.PP 
\fBomega\fP(1), \fBotp2ocp\fP(1)\&.
.PP 
\fIDraft Manual for the Omega System\fP (\fIomega-manual\&.dvi\fP)\&.
.PP 
Web page: <http://www\&.gutenberg\&.eu\&.org/omega/>
.PP 
.SH "BUGS" 
.PP 
None known, but report any bugs found to <omega@ens\&.fr> (mailing list)\&.
.PP 
.SH "AUTHOR" 
.PP 
\fBmkocp\fP is part of Omega\&.  The primary authors of Omega are John Plaice
<plaice@cse\&.unsw\&.edu\&.au> and Yannis Haralambous 
<yannis@fluxus-virus\&.com>\&.
.PP 
This manual page was written by C\&.M\&. Connelly
<cmc@debian\&.org>, for
the Debian GNU/Linux system\&.  It may be used by other distributions
without contacting the author\&.  Any mistakes or omissions in the
manual page are my fault; inquiries about or corrections to this
manual page should be directed to me (and not to the primary author)\&.
