.TH "mkofm" "1" "September 2000" "teTeX" "teTeX" 
.PP 
.SH "NAME" 
mkofm \- front end to \fBmktextfm\fP(1)
.SH "SYNOPSIS" 
.B mkofm
.I ARGS
.SH "DESCRIPTION" 
.PP 
\fBmkofm\fP takes all \fIARGS\fP and passes them to
\fBmktextfm\fP(1)\&.  For more information about appropriate
arguments, see \fBmktextfm\fP(1)\&.
.PP 
.SH "SEE ALSO" 
.PP 
\fBmktextfm\fP(1)
.PP 
.SH "BUGS" 
.PP 
None known\&.
.PP 
.SH "AUTHOR" 
.PP 
Author unknown\&.
.PP 
This manual page was written by C\&.M\&. Connelly
<cmc@debian\&.org>, for
the Debian GNU/Linux system\&.  It may be used by other distributions
without contacting the author\&.  Any mistakes or omissions in the
manual page are my fault; inquiries about or corrections to this
manual page should be directed to me (and not to the primary author)\&.
