.TH "mptopdf" "1" "01-01-2013" "version 1.4.1" "convert MetaPost to PDF"
.SH NAME
.B mptopdf
.SH SYNOPSIS
.B mptopdf [
.I OPTIONS ...
.B ] [
.I FILENAMES
.B ]
.SH DESCRIPTION
.B convert MetaPost to PDF
.SH OPTIONS
.TP
.B --metafun
use the metafun format to process the file (default is mpost)
.TP
.B --texexec
use texexec (context) to process text snippets
.TP
.B --latex
use latex to process text snippets
.SH AUTHOR
More information about ConTeXt and the tools that come with it can be found at:


.B "maillist:"
ntg-context@ntg.nl / http://www.ntg.nl/mailman/listinfo/ntg-context

.B "webpage:"
http://www.pragma-ade.nl / http://tex.aanhet.net

.B "wiki:"
http://contextgarden.net
